# Generated by Django 5.2.4 on 2025-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_teacher_id_students_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
