# Generated by Django 5.2.4 on 2025-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_students_email_alter_teachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='test123@demo.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default='test123@demo.com', max_length=254, unique=True),
        ),
    ]
