# Generated by Django 5.2.4 on 2025-07-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_students_email_alter_teachers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
