# Generated by Django 5.2.4 on 2025-07-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_rename_teacher_students_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='teacher_id',
            new_name='teacher_name',
        ),
    ]
