# Generated by Django 5.2.4 on 2025-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_rename_teacher_id_students_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='teacher_name',
            new_name='teacher',
        ),
    ]
